tealcrm/client/urls.py
from django.urls import path
from . import views

app_name='clients'

urlpatterns = [
    path('',views.clients_list,name='list'),
    path('<int:pk>/', views.clients_detail, name='detail'),
    path('add-client/', views.clients_add, name='add'),
    path('<int:pk>/edit/', views.clients_edit, name='edit'),
    path('<int:pk>/add-comment/', views.clients_detail, name='add_comment'),
    path('<int:pk>/add-file/', views.clients_detail, name='add_file'),
    path('<int:pk>/delete/', views.client_delete, name='delete'),
    path('export/', views.clients_export,name='export')


]

tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import index,about
from django.conf import settings
from django.conf.urls.static import static
from userprofile.forms import LoginForm, SignupForm

urlpatterns = [
    path('',index, name='index' ),
    path('dashboard/leads/',include('leads.urls') ),
    path('dashboard/clients/',include('client.urls') ),
    path('dashboard/team/',include('team.urls') ),
    path('dashboard/',include('userprofile.urls') ),
    path('dashboard/',include('dashboard.urls') ),
    path('about/',about, name='about' ),
    path('login/',views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tealcrm/team/urls.py
from django.urls import path
from . import views

app_name='team'

urlpatterns = [
    path('',views.teams_list,name='list'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/edit/',views.edit_team,name='edit'),
    path('<int:pk>/activate/',views.team_activate,name='activate'),
]

tealcrm/client/models.py
from django.db import models

# Create your models here.
from team.models import Team
from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):

    team = models.ForeignKey(Team, related_name='clients', on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    description=models.TextField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='clients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)

    def __str__(self):
        return self.name


class Comments(models.Model):
    team = models.ForeignKey(Team, related_name='client_comments', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True,null = True)
    created_by = models.ForeignKey(User, related_name='client_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username   

class ClientFile(models.Model):
    team = models.ForeignKey(Team, related_name='client_files', on_delete=models.CASCADE)
    client = models.ForeignKey(Client, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='clientfiles')
    created_by = models.ForeignKey(User, related_name='client_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

tealcrm/client/forms.py
from django import forms
from .models import Client,Comments,ClientFile

class AddClientForm(forms.ModelForm):
    class Meta:
        model=Client
        fields=('name','email','description')


class AddCommentForm(forms.ModelForm):
    class Meta:
        model=Comments
        fields=('content',)


class AddFileForm(forms.ModelForm):
    class Meta:
        model=ClientFile
        fields=('file',)

tealcrm/client/views.py
import csv
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .models import Client
from django.contrib import messages
from .forms import AddClientForm, AddCommentForm,AddFileForm
from team.models import Team
# Create your views here.

@login_required
def clients_export(request):
    clients= Client.objects.filter(created_by=request.user)


    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="clients .csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(["Client", "Description", "Created at", "Created by"])

    for client in clients:
        writer.writerow([client.name,client.description,client.created_at,client.created_by])

    return response






@login_required
def clients_list(request):
    clients= Client.objects.filter(created_by=request.user)
    return render(request,'clients/clients_list.html',{'clients':clients})


# @login_required
# def clients_detail(request,pk):
#     client = get_object_or_404(Client, created_by = request.user,pk=pk)
    # client = Client.objects.filter(created_by = request.user).get(pk=pk) -- keep commented 
    # team=Team.objects.filter(created_by=request.user)[0]



    # if request.method=='POST':
    #     form = AddCommentForm(request.POST)
    #     fileform = AddFileForm(request.POST,request.FILES)

    #     if form.is_valid() and fileform.is_valid():
    #         comment= form.save(commit=False)
    #         file= fileform.save(commit=False)
    #         comment.team= team
    #         file.team=team
    #         comment.created_by= request.user
    #         file.created_by= request.user
    #         comment.client=client
    #         file.client=client
    #         comment.save()
    #         file.save()

    #         return redirect('clients:detail',pk=pk)
    
    # else:
    #     form= AddCommentForm()
    #     fileform=AddFileForm()

    
    # return render(request,'clients/clients_detail.html',{'client':client,'form':form,'fileform':fileform})




@login_required
def clients_detail(request, pk):
    client = get_object_or_404(Client, created_by=request.user, pk=pk)
    

    if request.method == 'POST':
        # Check which form was submitted by identifying the button clicked
        if 'submit_comment' in request.POST:
            form = AddCommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.team = request.user.userprofile.active_team
                comment.created_by = request.user
                comment.client = client
                comment.save()
                return redirect('clients:detail', pk=pk)
            fileform = AddFileForm()  # Reinitialize file form to avoid errors
        elif 'submit_file' in request.POST:
            fileform = AddFileForm(request.POST, request.FILES)
            if fileform.is_valid():
                file = fileform.save(commit=False)
                file.team = request.user.userprofile.active_team
                file.created_by = request.user
                file.client = client
                file.save()
                return redirect('clients:detail', pk=pk)
            form = AddCommentForm()  # Reinitialize comment form to avoid errors
    else:
        form = AddCommentForm()
        fileform = AddFileForm()

    return render(request, 'clients/clients_detail.html', {'client': client, 'form': form, 'fileform': fileform})



# class AddFileView(View):
#     def post(self,request,*args,**kwargs):
#         pk=kwargs.get('pk')

#         form = AddFileForm(request.POST,request.FILES)
#         if form.is_valid():
#             team = Team.objects.filter(created_by=self.request.user)[0]
#             file= form.save(commit=False)
#             file.team=team
#             file.client_id=pk
#             file.created_by=request.user
#             file.save()

#         return redirect('clients:detail',pk=pk)













@login_required
def clients_edit(request,pk):
    client = get_object_or_404(Client, created_by = request.user,pk=pk)
    if request.method =='POST':
        form = AddClientForm(request.POST,instance=client)

        if form.is_valid():
            client.save()

            messages.success(request,'Changes Saved')

            return redirect('clients:list')
    else:
        form= AddClientForm(instance=client)

    return render(request, 'clients/clients_edit.html',{'form':form})




@login_required
def clients_add(request):
    user_profile = getattr(request.user, 'userprofile', None)
    active_team = user_profile.active_team if user_profile and user_profile.active_team else Team.objects.filter(created_by=request.user).first()
    if request.method =='POST':
        form = AddClientForm(request.POST)

        if form.is_valid():
            # team = self.request.user.userprofile.active_team
            client = form.save(commit = False)
            client.created_by = request.user
            client.team = active_team
            client.save()

            messages.success(request,'New Client was created')
            return redirect('clients:list')
    else:
        form= AddClientForm()
    return render(request, 'clients/client_add.html',{'form':form,'active_team':active_team})

@login_required
def client_delete(request,pk):
    client = get_object_or_404(Client, created_by = request.user,pk=pk)
    client.delete()

    messages.success(request,'Client was deleted')
    return redirect('clients:list')

tealcrm/client/templates/clients/add_client.html
{% extends 'core/base.html' %}

{% block title %}
Add Lead
{% endblock %}
{% block content %}

<h1 class="text-xl mb-3">Add Client</h1>
my Plan : {{team.plan.name}} <br>
max_clients in this plan : {{team.plan.max_clients}} <br>
total client in my account : {{team.clients.count}} <br>

{% if team.plan.max_clients > team.clients.count %}
<div class="px-3 py-6">

    <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
    {% else %}
    <div class="bg-red-100 text-red-500 p-3 rounded-xl mb-3">
        Your team have reached max number of clients for your plan. Please upgrade your plan to add more clients.
    </div>
    {% endif %}
    {% endblock %}

tealcrm/client/templates/clients/client_add.html
{% extends 'core/base.html' %}

{% block title %}
Add Lead
{% endblock %}
{% block content %}

<h1 class="text-xl mb-3">Add Client</h1>
my Plan : {{active_team.plan.name}} <br>
max_clients in this plan : {{active_team.plan.max_clients}} <br>
total client in my account : {{active_team.clients.count}} <br>

{% if active_team.plan.max_clients > active_team.clients.count %}
<div class="px-3 py-6">

    <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
    {% else %}
    <div class="bg-red-100 text-red-500 p-3 rounded-xl mb-3">
        Your team have reached max number of clients for your plan. Please upgrade your plan to add more clients.
    </div>
    {% endif %}
    {% endblock %}

tealcrm/client/templates/clients/clients_detail.html
{% extends 'core/base.html' %}

{% block title %}
{{client.name}} Details
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">{{client.name}}</h1>


    {% if client.description %}
    <p class="font-semibold">Description</p>
    <p class="mb-2">{{client.description}}</p>
    {% endif %}



    <p class="font-semibold">Created at</p>
    <p class="mb-2">{{client.created_at|date:"d/m/y (D) h:i"}}</p>

    <p class="font-semibold">Modified at</p>
    <p class="mb-6">{{client.modified_at}}</p>

    <hr class="my-4">


    <a class=" py-3 px-3 ml-3 rounded-xl bg-green-500" href=" {% url 'clients:edit' client.id%} ">Edit this client</a>
    <a class=" py-3 px-3 ml-3 rounded-xl bg-red-300" href="{% url 'clients:delete' client.id %}">Delete this client</a>



    <hr class="my-4">
    <h2 class="mb-6 text-xl">Comments</h2>
    <div class="space-y-4">

        {% for comment in client.comments.all %}
        <div class="bg-gray-300 px-6 py-6 rounded-xl ">
            <p><strong>{{comment.created_by}} </strong> @ {{comment.created_at}}</p>
           <p> {{comment.content}}</p>
        </div>
        {% endfor%}
    </div>





    <form action="{% url 'clients:add_comment' client.id %}" method="post">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-3 px-3 rounded-xl bg-blue-500" name="submit_comment">Submit Comment</button>

    </form>

    <hr class="my-4">




    <div class="space-y-4">

        {%for file in client.files.all %}
        <div class="bg-gray-300 px-6 py-6 rounded-xl ">
            <p class="mb-2"><strong>{{file.created_by}} </strong> @ {{file.created_at}}</p>

            <a href="{{file.file.url}}">View Client File ({{file.file.name}})</a>
        </div>
        {% endfor%}
    </div>




    <hr class="my-4">
    <h2 class="mb-6 text-xl">Files</h2>

    <form action="{% url 'clients:add_file' client.id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{fileform.as_p}}

        <button class="py-3 px-3 rounded-xl bg-blue-500"  name="submit_file">Upload File</button>

    </form>







    <a class=" py-3 px-5 bg-yellow-200" href="{% url 'clients:list'%}"> Back to client</a>

</div>
{% endblock %}

tealcrm/client/templates/clients/clients_edit.html
{% extends 'core/base.html' %}

{% block title %}
Edit Client
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">Edit Lead</h1>
    <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>

</div>
{% endblock %}

tealcrm/client/templates/clients/clients_list.html
{% extends 'core/base.html' %}

{% block title %}
Clients
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">Clients</h1>

    <a href="{% url 'clients:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">
        Add Client
    </a>
    <a href="{% url 'clients:export' %}" class="inline-block py-4 px-6 bg-teal-500 rounded-xl text-white">
        Export Clients
    </a>

    <div class="mt-6  flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
    </div>

    {% for client in clients %}
    <div class="flex justify-between">
        <p class="py-4 px-2 w-full {% cycle 'bg-blue-100' 'bg-pink-100'  %}">
            <a href="{% url 'clients:detail' client.id %}"> {{client.name}} </a></a>
        </p>
    </div>


    {% empty %}

    <p class="px-2 mt-3">There are no clients in the Database Right Now</p>
    {% endfor %}








</div>
{% endblock %}