tealcrm/leads/urls.py
from django.urls import path
from . import views

app_name='leads'

urlpatterns = [
    path('', views.LeadListView.as_view(), name='list'),
    path('<int:pk>/', views.LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.LeadDeleteView.as_view(), name='delete'),
    path('<int:pk>/edit/', views.LeadUpdateView.as_view(), name='edit'),
    path('<int:pk>/convert/', views.ConvertToClientView.as_view(), name='convert'),
    path('<int:pk>/add-comment/', views.AddCommentView.as_view(), name='add_comment'),
    path('<int:pk>/add-file/', views.AddFileView.as_view(), name='add_file'),
    path('add-lead/', views.LeadCreateView.as_view(),name='add'),
    path('export/', views.leads_export,name='export'),
]

tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import index,about
from django.conf import settings
from django.conf.urls.static import static
from userprofile.forms import LoginForm, SignupForm

urlpatterns = [
    path('',index, name='index' ),
    path('dashboard/leads/',include('leads.urls') ),
    path('dashboard/clients/',include('client.urls') ),
    path('dashboard/team/',include('team.urls') ),
    path('dashboard/',include('userprofile.urls') ),
    path('dashboard/',include('dashboard.urls') ),
    path('about/',about, name='about' ),
    path('login/',views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tealcrm/team/urls.py
from django.urls import path
from . import views

app_name='team'

urlpatterns = [
    path('',views.teams_list,name='list'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/edit/',views.edit_team,name='edit'),
    path('<int:pk>/activate/',views.team_activate,name='activate'),
]

tealcrm/leads/models.py
from django.db import models
from django.contrib.auth.models import User
from team.models import Team

# Create your models here.
class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    
    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High')
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost')
    )
    
    team = models.ForeignKey(Team, related_name='leads', on_delete=models.CASCADE)
    name=models.CharField(max_length=255)
    email=models.EmailField()
    description=models.TextField(blank=True,null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client=models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)

    def __str__(self):
        return self.name

class Comments(models.Model):
    team = models.ForeignKey(Team, related_name='lead_comments', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField(blank=True,null = True)
    created_by = models.ForeignKey(User, related_name='lead_comments', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username   


class LeadFile(models.Model):
    team = models.ForeignKey(Team, related_name='lead_files', on_delete=models.CASCADE)
    lead = models.ForeignKey(Lead, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='leadfiles')
    created_by = models.ForeignKey(User, related_name='lead_files', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.created_by.username

tealcrm/leads/forms.py
from django import forms
from .models import Lead,Comments,LeadFile

class AddLeadForm(forms.ModelForm):
    class Meta:
        model=Lead
        fields=('name','email','description','priority', 'status',)

class AddCommentForm(forms.ModelForm):
    class Meta:
        model=Comments
        fields=('content',)

class AddFileForm(forms.ModelForm):
    class Meta:
        model=LeadFile
        fields=('file',)

tealcrm/leads/views.py
import csv
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.shortcuts import render,redirect, get_object_or_404
# from .forms import AddLeadForm
from .forms import AddCommentForm,AddFileForm
from .models import Lead
from client.models import Client,Comments as ClientComment
from team.models import Team
from django.views import View
from django.views.generic import ListView,DetailView,DeleteView
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy



def leads_export(request):
    leads= Lead.objects.filter(created_by=request.user)

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(
        content_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="leads_data.csv"'},
    )

    writer = csv.writer(response)
    writer.writerow(["Name", "Description", "Status", "Priority", "Converted to client", "created at"])
    for lead in leads:
        writer.writerow([lead.name,lead.description,lead.status,lead.priority,lead.converted_to_client,lead.created_at])
    return response

# @login_required
# def leads_list(request):
#     leads=Lead.objects.filter(created_by=request.user)


#     return render(request,'leads/leads_list.html',{'leads':leads})

class LeadListView(LoginRequiredMixin,ListView):
    model = Lead
    template_name = 'leads/leads_list.html'
    context_object_name = 'leads'

    
    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Lead.objects.filter(created_by=self.request.user,converted_to_client=False)


# @login_required
# def leads_detail(request,pk):
#     lead = get_object_or_404(Lead, created_by = request.user,pk=pk)
#     # lead = Lead.objects.filter(created_by = request.user).get(pk=pk)

#     return render(request,'leads/leads_detail.html',{'lead':lead})

class LeadDetailView(LoginRequiredMixin,DetailView):
    model = Lead
    template_name = "leads/leads_detail.html"

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = AddCommentForm()
        context["fileform"] = AddFileForm()

        return context

    


    # def get_object(self):
    #     pk = self.kwargs.get('pk')
    #     return get_object_or_404(Lead,created_by=self.request.user,pk=pk)




    def get_queryset(self):
        return Lead.objects.filter(created_by=self.request.user, pk=self.kwargs.get('pk'))


# @login_required
# def leads_delete(request,pk):
#     lead = get_object_or_404(Lead, created_by = request.user,pk=pk)
#     lead.delete()

#     messages.success(request,'The lead was deleted')

#     return redirect('leads:list')

class LeadDeleteView(LoginRequiredMixin,DeleteView):
    model = Lead
    success_url = reverse_lazy('leads:list')

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    # def get_queryset(self):
    #      queryset = super(LeadDeleteView, self).get_queryset()

    #      return queryset.filter(created_by=self.request.user,pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)
        
        

class LeadUpdateView(LoginRequiredMixin,UpdateView): 
    # specify the model you want to use 
    model = Lead 
    fields = ('name','email','description','priority','status')
  
    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Edit Lead"	
        return context

    def get_queryset(self):
         queryset = super(LeadUpdateView, self).get_queryset()

         return queryset.filter(created_by=self.request.user,pk=self.kwargs.get('pk'))

    success_url = reverse_lazy("leads:list")


# @login_required
# def leads_edit(request,pk):
#     lead = get_object_or_404(Lead, created_by = request.user,pk=pk)
#     if request.method =='POST':
#         form = AddLeadForm(request.POST,instance=lead)

#         if form.is_valid():
#             lead.save()

#             messages.success(request,'Changes Saved')

#             return redirect('leads:list')
#     else:
#         form= AddLeadForm(instance=lead)

#     return render(request, 'leads/leads_edit.html',{'form':form})


class LeadCreateView(LoginRequiredMixin,CreateView):
    model = Lead
    fields = ('name','email','description','priority','status')
    # template_name='leads/add_lead.html'	

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    success_url = reverse_lazy("leads:list")


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        team= self.request.user.userprofile.active_team
        context["team"] = team
        context["title"] = "Add Lead"	
        return context
    



    def  form_valid(self, form):
        # team = Team.objects.filter(created_by=self.request.user)[0]

        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.team=self.request.user.userprofile.active_team
        self.object.save()
        return redirect(self.get_success_url())

class AddFileView(LoginRequiredMixin,View):
    def post(self,request,*args,**kwargs):
        pk=kwargs.get('pk')

        form = AddFileForm(request.POST,request.FILES)
        if form.is_valid():
            # team = Team.objects.filter(created_by=self.request.user)[0]
            # team = request.user.userprofile.active_team
            file= form.save(commit=False)
            file.team=self.request.user.userprofile.active_team
            file.lead_id=pk
            file.created_by=request.user
            file.save()

        return redirect('leads:detail',pk=pk)









class AddCommentView(LoginRequiredMixin,View):
    def post(self,request,*args,**kwargs):
        pk=kwargs.get('pk')
        # content = request.POST.get('content')

        # print(content)
        # print(pk)

        form = AddCommentForm(request.POST)
        if form.is_valid():
            # team = Team.objects.filter(created_by=self.request.user)[0]
            comment= form.save(commit=False)
            comment.team= self.request.user.userprofile.active_team
            comment.created_by= request.user
            comment.lead_id=pk
            comment.save()

        return redirect('leads:detail',pk=pk)


    




# @login_required
# def add_lead(request):
#     team= Team.objects.filter(created_by=request.user)[0]

#     if request.method =='POST':
#         form = AddLeadForm(request.POST)

#         if form.is_valid():
#             team= Team.objects.filter(created_by=request.user)[0]
#             lead = form.save(commit = False)
#             lead.created_by = request.user
#             lead.team=team
#             lead.save()

#             messages.success(request,'New lead was created')

#             return redirect('leads:list')
#     else:
#         form= AddLeadForm()
#     return render(request, 'leads/add_lead.html',{'form':form,'team':team})


class ConvertToClientView(LoginRequiredMixin,View):
    def get(self,request,pk):
        lead =get_object_or_404(Lead,created_by=request.user,pk=pk)
        team = self.request.user.userprofile.active_team

        client=Client.objects.create(
            name=lead.name,
            email=lead.email,
            description=lead.description,
            created_by=request.user, 
            team=team
        )

        lead.converted_to_client=True
        lead.save()


# converting lead comment to client comment

        comments = lead.comments.all()

        for comment in comments:
           ClientComment.objects.create(
                client=client,
                content= comment.content,
                created_by=comment.created_by,
                team=team
           )

        messages.success(request,'The Lead was converted to Client')

        return redirect('leads:list')


# @login_required
# def convert_to_client(request,pk):

#     lead =get_object_or_404(Lead,created_by=request.user,pk=pk)
#     team= Team.objects.filter(created_by=request.user)[0]

#     client=Client.objects.create(
#         name=lead.name,
#         email=lead.email,
#         description=lead.description,
#         created_by=request.user, 
#         team=team
#     )

#     lead.converted_to_client=True
#     lead.save()

#     messages.success(request,'The Lead was converted to Client')

#     return redirect('leads:list')

tealcrm/leads/templates/leads/add_lead.html
{% extends 'core/base.html' %}

{% block title %}
Add Lead
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">Add Lead</h1>
    My Plan : {{team.plan.name}} <br>
    max_leads in this plan : {{team.plan.max_leads}} <br>
    total lead in my account : {{team.leads.count}} <br>

    {% if team.plan.max_leads > team.leads.count %} <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
    {% else %}
    <div class="bg-red-100 text-red-500 p-3 rounded-xl mb-3">
        Your team have reached max number of leads for your plan. Please upgrade your plan to add more leads.
    </div>
    {% endif %}
</div>
{% endblock %}

tealcrm/leads/templates/leads/lead_form.html
{% extends 'core/base.html' %}

{% block title %}
{{title}}

{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">{{title}}</h1>

    {% if team.plan.max_leads > team.leads.count or title == 'Edit Lead' %} 
    <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>
    {% else %}
    <div class="bg-red-100 text-red-500 p-3 rounded-xl mb-3">
        Your team have reached max number of leads for your plan. Please upgrade your plan to add more leads.
    </div>
    {% endif %}
    <!-- <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form> -->

</div>
{% endblock %}

tealcrm/leads/templates/leads/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}
{{lead.name}} Details
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">{{lead.name}}</h1>


    {% if lead.description %}
    <p class="font-semibold">Description</p>
    <p class="mb-2">{{lead.description}}</p>
    {% endif %}

    <p class="font-semibold">Priority</p>
    <p class="mb-2">{{lead.get_priority_display}}</p>

    <p class="font-semibold">Status</p>
    <p class="mb-2">{{lead.get_status_display}}</p>

    <p class="font-semibold">Created at</p>
    <p class="mb-2">{{lead.created_at|date:"d/m/y (D) h:i"}}</p>

    <p class="font-semibold">Modified at</p>
    <p class="mb-6">{{lead.modified_at}}</p>

    <hr class="my-4">


    <a class=" py-3 px-3 ml-3 rounded-xl bg-blue-500" href="{% url 'leads:convert' lead.id %}">Convert to Client</a>
    <a class=" py-3 px-3 ml-3 rounded-xl bg-green-500" href="{% url 'leads:edit' lead.id %}">Edit this Lead</a>
    <a class=" py-3 px-3 ml-3 rounded-xl bg-red-300" href="{% url 'leads:delete' lead.id %}">Delete this Lead</a>

    <hr class="my-4">
    <h2 class="mb-6 text-xl">Comments</h2>
    <div class="space-y-4">

        {% for comment in lead.comments.all %}
        <div class="bg-gray-300 px-6 py-6 rounded-xl ">
            <p><strong>{{comment.created_by}} </strong> @ {{comment.created_at}}</p>
            {{comment.content}}
        </div>
        {% endfor%}
    </div>





    <form action="{% url 'leads:add_comment' lead.id %}" method="post">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-3 px-3 rounded-xl bg-blue-500">Submit</button>

    </form>


    <div class="space-y-4">

        {%for file in lead.files.all %}
        <div class="bg-gray-300 px-6 py-6 rounded-xl ">
            <p class="mb-2"><strong>{{file.created_by}} </strong> @ {{file.created_at}}</p>

            <a href="{{file.file.url}}">View File ({{file.file.name}})</a>
        </div>
        {% endfor%}
    </div>




    <hr class="my-4">
    <h2 class="mb-6 text-xl">Files</h2>

    <form action="{% url 'leads:add_file' lead.id%}" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{fileform.as_p}}

        <button class="py-3 px-3 rounded-xl bg-blue-500">Submit</button>

    </form>





    <a class=" py-3 px-5 bg-yellow-200" href="{% url 'leads:list'%}"> Back to Leads</a>

</div>
{% endblock %}

tealcrm/leads/templates/leads/leads_list.html
{% extends 'core/base.html' %}

{% block title %}
Leads
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">Leads</h1>

    <a href="{% url 'leads:add' %}" class="inline-block py-4 px-6 bg-teal-600 rounded-xl text-white">
        Add Lead
    </a>
    <a href="{% url 'leads:export' %}" class="inline-block py-4 px-6 bg-teal-500 rounded-xl text-white">
        Export Leads
    </a>

    <div class="mt-6  flex justify-between">
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Name</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Priority</p>
        <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Status</p>
    </div>

    {% for lead in leads %}
    <div class="flex justify-between">
        <p class="py-4 px-2 w-full {% cycle 'bg-blue-100' 'bg-pink-100'  %}">
            <a href="{% url 'leads:detail' lead.id %}"> {{lead.name}} </a></a>
        </p>
        <p class="py-4 px-2 w-full {% cycle 'bg-blue-100' 'bg-pink-100'  %}">{{lead.get_priority_display}}</p>
        <p class="py-4 px-2 w-full {% cycle 'bg-blue-100' 'bg-pink-100'  %}">{{lead.get_status_display}}</p>
    </div>


    {% empty %}

    <p class="px-2 mt-3">There are no leads in the Database Right Now</p>
    {% endfor %}








</div>
{% endblock %}