tealcrm/tealcrm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from core.views import index,about
from django.conf import settings
from django.conf.urls.static import static
from userprofile.forms import LoginForm, SignupForm

urlpatterns = [
    path('',index, name='index' ),
    path('dashboard/leads/',include('leads.urls') ),
    path('dashboard/clients/',include('client.urls') ),
    path('dashboard/team/',include('team.urls') ),
    path('dashboard/',include('userprofile.urls') ),
    path('dashboard/',include('dashboard.urls') ),
    path('about/',about, name='about' ),
    path('login/',views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

tealcrm/team/urls.py
from django.urls import path
from . import views

app_name='team'

urlpatterns = [
    path('',views.teams_list,name='list'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/edit/',views.edit_team,name='edit'),
    path('<int:pk>/activate/',views.team_activate,name='activate'),
]

tealcrm/team/models.py
from django.contrib.auth.models import User
from django.db import models

class Plan(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.TextField(blank=True,null=True)
    max_leads = models.IntegerField()
    max_clients = models.IntegerField()
    def __str__(self):
        return self.name


class Team(models.Model):
    plan = models.ForeignKey(Plan,related_name='teams',on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User,related_name='created_teams' ,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    members = models.ManyToManyField(User)
    def __str__(self):
        return self.name

tealcrm/team/forms.py
from django import forms
from .models import Team

class TeamForm(forms.ModelForm):
    class Meta:
        model= Team
        fields = ['name',]

tealcrm/team/views.py
from django.contrib import messages
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Team
from .forms import TeamForm



@login_required
def teams_list(request):
    teams = Team.objects.filter(members__in=[request.user])

    return render(request, 'team/teams_list.html',{'teams':teams})

@login_required
def team_activate(request,pk):
    team = Team.objects.filter(members__in=[request.user]).get(pk=pk)
    userprofile = request.user.userprofile
    userprofile.active_team=team
    userprofile.save()

    return redirect('team:detail',pk=pk)





@login_required
def detail(request,pk):
    team=get_object_or_404(Team,members__in=[request.user],pk=pk)
    return render(request, 'team/details.html',{'team':team})


@login_required
def edit_team(request,pk):
    team = get_object_or_404(Team,created_by=request.user,pk=pk)


    if request.method == 'POST':
        form = TeamForm(request.POST,instance=team)
        if form.is_valid():
            form.save()

            messages.success(request,'Team updated successfully')
            return redirect('userprofile:myaccount')
    else:
        form = TeamForm()

    return render(request,'team/edit_team.html',{'team':team,'form':form})

tealcrm/team/templates/team/details.html
{% extends 'core/base.html' %}

{% block title %}
{{team.name}}
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-6"> Team -{{team.name}}</h1>

    <a href="{% url 'team:list' %}" class="inline-block py-4 px-6 bg-teal-800 rounded-xl text-white">Switch Team</a>

    
    {% if team.created_by == request.user %}
    <a href="{% url 'team:edit' team.id %}"
    class="inline-block py-4 px-6 bg-blue-500 rounded-xl text-white">Edit</a>
    
    {% endif %}
    
    <h4 class="text-xl mb-3"><strong>Team owner :</strong> -{{team.created_by}}</h1>

        <hr class="my-6">
        <h2 class="font-semibold mt-3">Team Members :</h2>
        {% for member in team.members.all%}
        <p>{{member.username}}</p>
        {% endfor%}

</div>
{% endblock %}

tealcrm/team/templates/team/edit_team.html
{% extends 'core/base.html' %}

{% block title %}
Edit Team
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-xl mb-3">Edit Team -{{team.name}}</h1>
    <form method="POST" action="." class="space-y-3">
        {% csrf_token %}

        {{form.as_p}}

        <button class="py-4 px-8 bg-teal-500 text-white rounded-xl">Submit</button>
    </form>

</div>
{% endblock %}

tealcrm/team/templates/team/teams_list.html
{% extends 'core/base.html' %}

{% block title %}
Team List
{% endblock %}
{% block content %}
<div class="px-3 py-6">
    <h1 class="text-2xl mb-6">Teams</h1>

    <div class="grid grid-cols-4 gap-4">
        {% for team in teams %}
        <div class="{% if team == active_team %}bg-emerald-100{% else%} bg-gray-100 {% endif %} rounded-xl p-6">
            <h2 class="mb-4 text-xl">{{team.name}}</h2>



            {% if team == active_team %}
            <a href="{% url 'team:detail' team.id %}" class="py-4 px-6 inline-block bg-teal-600 rounded-xl text-white">Team Details</a>
            {% else %}
            <a href="{% url 'team:activate' team.id %}" class="py-4 px-6 inline-block bg-teal-600 rounded-xl text-white">Activate Team</a>
            {% endif %}
        </div>
        {% endfor %}

    </div>

</div>
{% endblock %}